# hello 테스트
GET localhost:8080/api/code/role
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJBdXRoIiwiaXNzIjoiQVRTIiwiZXhwIjoxNjM3MDc5OTExLCJpYXQiOjE2MzQ0ODc5MTEsIm1lbWJlcklkIjoiYWRtaW4ifQ.CdXYZxenPaypKdXa4yrMmy4LPCu5pkGoYdKqkcp31YFXH48GY4FX6oFKNvi-ebtPwvgL3aLsAuqwj63tNNSyxA
Content-Type: application/json